// Code generated by "stringer -type=NodeKey -trimprefix=Key -output ./node_key_string.go"; DO NOT EDIT.

package ast

import "strconv"

const _NodeKey_name = "StmtsName"

var _NodeKey_index = [...]uint8{0, 5, 9}

func (i NodeKey) String() string {
	i -= 1
	if i < 0 || i >= NodeKey(len(_NodeKey_index)-1) {
		return "NodeKey(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _NodeKey_name[_NodeKey_index[i]:_NodeKey_index[i+1]]
}
