// Code generated by "stringer -type=NodeType -trimprefix=Type -output ./node_type_string.go"; DO NOT EDIT.

package ast

import "strconv"

const _NodeType_name = "StmtFuncStmtExprName"

var _NodeType_index = [...]uint8{0, 8, 16, 20}

func (i NodeType) String() string {
	i -= 1
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
